# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/dhersz/dhmisc
    rev: v0.0.0.9012
    hooks:
    -   id: mod-codemeta-description-updated
    -   id: mod-readme-rmd-rendered
    -   id: version-bumped
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
